version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    networks:
      - backend
    restart: always
    volumes:
      - .:/app  

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: always

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
